### ISSUE TITLE
support glob for file execution

### ISSUE THREAD

**Issue by AugustinMauroy** [RafaelGSS/bench-node-cli#1]
we should found a way to run multiple bench on a same command. Such as nodejs test runner

**Comment by RafaelGSS** [comment]
Why not use two terminals? Or simply:

```console
$ bench-node-cli bench1.js & bench-node-cli bench2.js
```

**Comment by AugustinMauroy** [comment]
I want to use it there https://github.com/JakobJingleheimer/nodejs-loaders/issues/17

So I would like to use something like that 

```bash
$ bench-node-cli **/**.bench.mjs
```

**Comment by RafaelGSS** [comment]
hmm, I suspect that would be better handled directly on nodejs-loaders repository if you write a bash script that does it. 

Something like:

```bash
files=(**/*.bench.mjs)

for file in "${files[@]}"; do
  echo "Running bench-node-cli for $file..."
  bench-node-cli "$file"
done
```

**Comment by AugustinMauroy** [comment]
It's an interesting solution. But I was wondering if a blog on the client would be useful for users, as it would give the same experience as the internal test runner.

**Comment by RafaelGSS** [comment]
Well, you can achieve the same behaviour running via Node.js (child_process).

**Comment by AugustinMauroy** [comment]
yeah !
